### PR TITLE
require GTK+ 3.22 and GLib 2.50

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by monsta** [comment]
Same intltool bug as mentioned in https://github.com/mate-desktop/mate-control-center/pull/328.

This package is quite specific... I have it installed only in one VM, but I didn't even try to configure Apache for it. It also has a bluetooth sharing support which is broken since it relies on the long gone mate-bluetooth package.
I'm not sure what to do with this package in the future (maybe drop it, hand it to someone who would want to maintain it). For now, I did the same as in all other packages for 1.20.

**Comment by lukefromdc** [comment]
I got that same bug in several other packages trying to test distcheck, so gave up on that. Glad to hear that's all it is

**Comment by raveit65** [comment]
Don't think that m-u-s use normal ports of apache.
For getting m-u-s working you or an admin have to open all ports > 1023 in your firewall.
M-u-s don't use a fixed port.
Gnome did that already with their workstation firewall config in fedora to fix using gnome-user-share.
As i don't agree with this insecure measure i droped mate-user-share from fedora a while ago, in favor of using secure server-firewall-config from fedora.

**Comment by clefebvre** [comment]
Looks good.

**Pull request merged**
