### PR TITLE
gtk3: Port from libunique to GtkApplication

### LINKED ISSUE #38: Migrate mate-user-share to GtkApplication
Debian has raised the following bug:

  * **mate-user-share** - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827231

This MATE component needs migrating to GtkApplication:

  * https://developer.gnome.org/gtk3/3.20/gtk-migrating-unique-GtkApplication.html

### PR DESCRIPTION
**Pull request by sc0w**
based on gnome-user-share commit:
https://git.gnome.org/browse/gnome-user-share/commit/?id=70577007a8ecce66bf6b547bda863235bc1d6f48

Fixes #38

### CODE REVIEW

**Comment by sc0w** [comment]
don't works the gtk2 build, what is my mistake?

**Comment by raveit65** [comment]
Problem is to use gtk version checks in configure, which does not work.
```
case "$with_gtk" in
  2.0) GTK_API_VERSION=2.0
       GTK_REQUIRED_VERSION=2.24.0
       CANBERRA_API_VERSION=
       UNIQUE_API_VERSION=1.0
       ;;
  3.0) GTK_API_VERSION=3.0
       GTK_REQUIRED_VERSION=3.0.0
       CANBERRA_API_VERSION=3
       ;;
esac
```
This should be sufficient.
And please don't use a negative form for the versions checks.
Everybody expect this form in our code.
#if GTK_CHECK_VERSION (3, 0, 0)
#else
#endif
We use the negative form only for a condition without 'else', mostly for gtk2-only code.

**Comment by raveit65** [comment]
Not sure what to do with that line in configure
```
PKG_CHECK_MODULES(USER_SHARE_CONFIG, glib-2.0 >= 2.15.2 gio-2.0 >= 2.25.0 gtk+-$GTK_API_VERSION >= $GTK_REQUIRED_VERSION unique-$UNIQUE_API_VERSION)
```
@monsta thoughts?

**Comment by sc0w** [comment]
@raveit65 

> Problem is to use gtk version checks in configure, which does not work.

yes, stupid mistake xD

> And please don't use a negative form for the versions checks.
> We use the negative form only for a condition without 'else', mostly for gtk2-only code.

ok, no problem

> Not sure what to do with that line in configure
> PKG_CHECK_MODULES(USER_SHARE_CONFIG, glib-2.0 >= 2.15.2 gio-2.0 >= 2.25.0 gtk+-$GTK_API_VERSION >= $GTK_REQUIRED_VERSION unique-$UNIQUE_API_VERSION)

It works with:
```diff
if test "$UNIQUE_API_VERSION" = "1.0"; then
	PKG_CHECK_MODULES(USER_SHARE_CONFIG, glib-2.0 >= 2.15.2 gio-2.0 >= 2.25.0 gtk+-$GTK_API_VERSION >= $GTK_REQUIRED_VERSION unique-$UNIQUE_API_VERSION)
else
	PKG_CHECK_MODULES(USER_SHARE_CONFIG, glib-2.0 >= 2.15.2 gio-2.0 >= 2.25.0 gtk+-$GTK_API_VERSION >= $GTK_REQUIRED_VERSION)
fi

**Pull request closed without merging**
